services:
    php:
        build:
            context: .
            target: app_php
        volumes:
            - .:/app

    caddy:
        build:
            context: .
            target: app_caddy
        ports:
            - 80:80
        volumes:
            - .:/app
