services:
    php:
        build:
            context: .
            target: app_php
        volumes:
            - .:/app

    postgres:
        image: postgres:16.3-alpine
        ports:
            - 5432
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-app}
            POSTGRES_USER: ${POSTGRES_USER:-app}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data:rw

    caddy:
        build:
            context: .
            target: app_caddy
        ports:
            - 80:80
        volumes:
            - .:/app
