services:
    php:
        build:
            context: .
            target: app_php
        volumes:
            - .:/app

    caddy:
        build:
            context: .
            target: app_caddy
        ports:
            - 80:80
            - 443:443
        volumes:
            - .:/app

    postgres:
        image: postgres:16.3-alpine
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
        volumes:
            - ./docker/postgres/data:/var/lib/postgresql/data:rw
